# Generated by Django 2.0.7 on 2019-05-12 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_networking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete='cascade', related_name='plans', to='social_networking_app.Post')),
                ('user', models.ForeignKey(null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
    ]
